default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shoestore_inventory_dashboard_development

test:
  <<: *default
  database: shoestore_inventory_dashboard_test

production:
  <<: *default
  database: shoestore_inventory_dashboard_production
  username: shoestore_inventory_dashboard
  password: <%= ENV["SHOESTORE_INVENTORY_DASHBOARD_DATABASE_PASSWORD"] %>
